In [207]:
import pandas as pd
import numpy as np

In [208]:
pd.options.display.float_format = '{:,.2f}'.format

In [209]:
pd.set_option('display.max_rows', 100)

### Problema 1
Vamos praticar gerar matrizes e fazer operações com as linhas e colunas:

(a) Crie uma matriz A com as dimensões (5, 4) e elementos aleatórios variando entre 0 e 50, com o 50 incluso;

__Dica:__ Utilize as funções `np.random.randint` e `np.reshape`

(b) Retorne a média do vetor

(c) Retorne os menores valores de cada coluna;

(d) Retorne os maiores valores de cada linha.

In [210]:
# (A)
matriz_a = np.random.randint(51,size=(5,4))
print(matriz_a)

# (B)
matriz_a.mean()

[[31 28 27 34]
 [24 14 43 42]
 [34 44 50 16]
 [43 39 42  4]
 [ 8  6 43 47]]


30.95

In [211]:
df = pd.DataFrame(matriz_a)
# min coluna (C)
df.min(axis=0) 

0     8
1     6
2    27
3     4
dtype: int32

In [212]:
# max linha (D)
df.max(axis=1) 

0    34
1    43
2    50
3    43
4    47
dtype: int32

### Problema 2

Crie um objeto DataFrame que contenha os dados da tabela abaixo, os quais se referem ao peso, altura e idade de cinco pessoas:


| Peso (kg) | Altura (cm) | Idade (anos) |
|-----------|-------------|--------------|
|  47 | 161	| 31 |
|  80 | 170	| 21 |
|  60 | 175	| 16 |
|  90 | 162	| 28 |
| 100 | 185	| 23 |
| 147 | 189 | 32 |

Com base no DataFrame criado, realize o que for pedido nos itens abaixo:

(a) Visualize apenas os dados da coluna que contém a altura das pessoas;

(b) Obtenha a idade média das pessoas;

(c) Obtenha os dados das pessoas que estão abaixo da altura média;

(d) Crie um nova coluna no DataFrame que contenha o IMC (Índice de Massa Corporal) de cada pessoa;

__Obs.:__ A fórmula para o IMC é dada por IMC = Peso/(Altura)² com o peso em kg e a altura em metros.

(e) Remova a coluna que contém a idade das pessoas;

(f) Crie uma nova coluna chamada Classificação, que contenha a classificação de cada indivíduo, de acordo com o seu IMC. Para isso, consulte a tabela abaixo.

| IMC             | Classificação |
|-----------------|---------------|
Menor que 18,5    | Subpeso |
Entre 18,5 e 24,9 | Normal |
Entre 25,0 e 29,9 | Sobrepeso |
Entre 30,0 e 39,9 | Obesidade Grau I |
Maior que 40,0    | Obesidade Grau II |

(g) Salve esses dados do DataFrame em um arquivo csv.

In [213]:
dados = {'Peso': [47,80,60,90,100,147], 'Altura': [161, 170,175,162,185,189],'Idade':[31,21,16,28,23,32]}

df = pd.DataFrame(data=dados)

In [214]:
# (A)
df['Altura']

0    161
1    170
2    175
3    162
4    185
5    189
Name: Altura, dtype: int64

In [215]:
# (B)
media_idade = np.mean(dados['Idade'])
print(media_idade)

25.166666666666668


In [216]:
# (C)
media_altura = np.mean(dados['Altura'])
df[df['Altura'] < media_altura]

Peso  Altura  Idade
0    47     161     31
1    80     170     21
3    90     162     28

In [217]:
# (D)
# Obs.: A fórmula para o IMC é dada por IMC = Peso/(Altura)² com o peso em kg e a altura em metros.
df['IMC'] = df['Peso']/(df['Altura']/100)**2 

df

Peso  Altura  Idade   IMC
0    47     161     31 18.13
1    80     170     21 27.68
2    60     175     16 19.59
3    90     162     28 34.29
4   100     185     23 29.22
5   147     189     32 41.15

In [218]:
# (E)
df = df.drop('Idade', axis = 1)
df

Peso  Altura   IMC
0    47     161 18.13
1    80     170 27.68
2    60     175 19.59
3    90     162 34.29
4   100     185 29.22
5   147     189 41.15

In [219]:
def classif(imc):
    if imc < 18.5:
        return 'Subpeso'
    elif imc < 24.9:
        return 'Normal'
    elif imc < 29.9:
        return 'Sobrepeso'
    elif imc < 39.9:
        return 'Obesidade Grau I'
    else:
        return 'Obesidade Grau II'

In [220]:
# (F)
df['Classificação'] = df.apply(lambda x: classif(x['IMC']), axis=1)
df

Peso  Altura   IMC      Classificação
0    47     161 18.13            Subpeso
1    80     170 27.68          Sobrepeso
2    60     175 19.59             Normal
3    90     162 34.29   Obesidade Grau I
4   100     185 29.22          Sobrepeso
5   147     189 41.15  Obesidade Grau II

### Problema 3

O arquivo avocado.xlsx consiste em um dataset que contém dados sobre vendas de abacates  em diversas regiões dos Estados Unidos. Essa dataset contém as seguintes colunas:

| Coluna | Descrição |
|--------|-----------|
| Date | data da observação |
| AveragePrice | preço médio de um único abacate |
| year | ano |
| region | cidade ou região da observação |
| Total Volume | volume total de abacates vendidos |

Além das informações acima, contidas no arquivo avocado.xlsx, o tipo do abacate (convencional ou orgânico) também seria uma informação importante para a sua análise. Suponhamos que você conseguiu essas informações para cada uma das observações do arquivo avocado.csv, na mesma ordem, e salvou-as no arquivo avocado_type.xlsx. Portanto, tudo o que você precisa é juntar esses dois arquivos em um mesmo DataFrame.

Com o DataFrame criado, obtenha o que é solicitado nos itens elencados abaixo:




In [221]:
df_avocado = pd.read_csv("./avocado.csv",delimiter=';')
df_avocado_type = pd.read_excel("./avocado_type.xlsx")
df_avocado['type'] = df_avocado_type

In [222]:
df_avocado.shape

(18249, 6)

(a) A quantidade de abacates do tipo convecional e do tipo orgânico.

In [223]:
df_avocado.groupby(['type']).size()

type
convencional    9114
orgânico        9135
dtype: int64


(b) A quantidade de registros (linhas) de abacates vendidos para cada região ordenada da maior venda para a menor.

In [224]:
#Pular

(c) Para que todos os labels das colunas fiquem padronizados, renomeie aqueles que estão iniciando em letra minúscula para que iniciem em letra maiúscula, trocando espaço por _ e adicionando _ como separação de texto.

In [225]:
df_avocado = df_avocado.rename(columns={'AveragePrice': 'Average_Price', 'Total Volume': 'Total_Volume', 'year': 'Year', 'region': 'Region', 'type': 'Type'}) 

(d) Essa dado possui duplicados? Se sim, remova-os do dataset.

In [228]:
df_avocado.duplicated().sum()
# Não há duplicados

0

(e) Retire dos dados a região 'TotalUS'

In [229]:
df_avocado = df_avocado[df_avocado['Region'] != 'TotalUS']

(g) Apresente as regiões que mais venderam abacate em todo o período em ordem decrescente.

In [230]:
df_avocado.groupby(['Region']).agg({'Total_Volume':np.sum}).sort_values(by="Total_Volume",ascending=False)

Total_Volume
Region                              
West                1,086,779,155.75
California          1,028,981,653.17
SouthCentral        1,011,279,618.83
Northeast             713,280,909.56
Southeast             615,238,409.11
GreatLakes            589,642,549.29
Midsouth              508,349,357.20
LosAngeles            507,896,547.63
Plains                311,188,529.11
NewYork               240,734,127.53
DallasFtWorth         208,419,286.55
Houston               203,167,867.80
PhoenixTucson         195,643,312.50
WestTexNewMexico      144,521,839.78
Denver                138,902,535.99
SanFrancisco          135,830,191.78
BaltimoreWashington   134,713,919.32
Chicago               133,702,338.51
Portland              110,552,211.60
Seattle               109,214,177.96
MiamiFtLauderdale      97,673,224.03
Boston                 97,273,984.83
SanDiego               89,791,919.69
Atlanta                88,605,118.85
Sacramento             75,163,746.86
Philadelphia           71,838,798.18
NorthernNewEngland     71,532,894.11
Tampa                  66,004,539.31
Detroit                63,422,419.38
SouthCarolina          60,753,772.90
Orlando                58,660,703.89
LasVegas               54,376,906.40
HartfordSpringfield    50,670,537.46
RaleighGreensboro      48,202,731.66
NewOrleansMobile       45,695,136.58
CincinnatiDayton       44,522,007.57
RichmondNorfolk        42,230,851.45
HarrisburgScranton     41,808,858.68
Nashville              35,612,089.23
Charlotte              35,555,544.42
StLouis                32,072,833.33
Indianapolis           30,263,391.43
GrandRapids            30,211,735.93
Columbus               29,993,361.42
Jacksonville           28,790,004.74
Roanoke                25,042,010.81
BuffaloRochester       22,962,470.40
Pittsburgh             18,806,345.81
Louisville             16,097,002.40
Albany                 16,067,799.97
Spokane                15,565,275.48
Boise                  14,413,187.75
Syracuse               10,942,667.68

(h) Calcule o volume total de abacates vendidos para cada tipo e ano.

In [231]:
df_avocado.groupby(['Type','Year']).agg({'Total_Volume':np.sum})

Total_Volume
Type         Year                 
convencional 2015 1,405,835,526.60
             2016 1,538,913,526.12
             2017 1,505,463,914.14
             2018   433,710,441.83
orgânico     2015 1,322,377,914.02
             2016 1,462,817,222.93
             2017 1,564,148,221.75
             2018   425,395,644.21

(f) existe alguma região que foi a maior responsável pela queda na produção de 2018?

In [232]:
df_avocado[df_avocado['Year'] == 2018].groupby(['Region']).agg({'Total_Volume':np.sum}).sort_values(by="Total_Volume",ascending=True).head(1)

Total_Volume
Region                
Syracuse  1,046,987.66

(g) Qual cidade menos faturou com a venda de abacates?

In [233]:
df_avocado['Faturamento'] = df_avocado['Total_Volume'] * df_avocado['Average_Price']

In [234]:
df_avocado.groupby(['Region']).agg({'Faturamento':np.sum}).sort_values(by="Faturamento",ascending=True).head(1)

Faturamento
Region                
Syracuse 15,205,192.60

### Problema 4

Com base no dataset 'Video_Games_Sales.csv' responda:


In [235]:
df_games = pd.read_csv("./Video_Games_Sales.csv", delimiter=';')
#df_games.dropna(inplace=True)
#df_games = df_games.astype({'Year_of_Release': int})

In [236]:
df_games

Name Platform  Year_of_Release         Genre  \
0                         Wii Sports      Wii         2,006.00        Sports   
1                  Super Mario Bros.      NES         1,985.00      Platform   
2                     Mario Kart Wii      Wii         2,008.00        Racing   
3                  Wii Sports Resort      Wii         2,009.00        Sports   
4           Pokemon Red/Pokemon Blue       GB         1,996.00  Role-Playing   
...                              ...      ...              ...           ...   
16714  Samurai Warriors: Sanada Maru      PS3         2,016.00        Action   
16715               LMA Manager 2007     X360         2,006.00        Sports   
16716        Haitaka no Psychedelica      PSV         2,016.00     Adventure   
16717               Spirits & Spells      GBA         2,003.00      Platform   
16718            Winning Post 8 2016      PSV         2,016.00    Simulation   

          Publisher  NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  \
0          Nintendo     41.36     28.96      3.77         8.45         82.53   
1          Nintendo     29.08      3.58      6.81         0.77         40.24   
2          Nintendo     15.68     12.76      3.79         3.29         35.52   
3          Nintendo     15.61     10.93      3.28         2.95         32.77   
4          Nintendo     11.27      8.89     10.22         1.00         31.37   
...             ...       ...       ...       ...          ...           ...   
16714    Tecmo Koei      0.00      0.00      0.01         0.00          0.01   
16715   Codemasters      0.00      0.01      0.00         0.00          0.01   
16716  Idea Factory      0.00      0.00      0.01         0.00          0.01   
16717       Wanadoo      0.01      0.00      0.00         0.00          0.01   
16718    Tecmo Koei      0.00      0.00      0.01         0.00          0.01   

       Critic_Score  Critic_Count  User_Score  User_Count Developer Rating  
0             76.00         51.00        8.00      322.00  Nintendo      E  
1               NaN           NaN         NaN         NaN       NaN    NaN  
2             82.00         73.00        8.30      709.00  Nintendo      E  
3             80.00         73.00        8.00      192.00  Nintendo      E  
4               NaN           NaN         NaN         NaN       NaN    NaN  
...             ...           ...         ...         ...       ...    ...  
16714           NaN           NaN         NaN         NaN       NaN    NaN  
16715           NaN           NaN         NaN         NaN       NaN    NaN  
16716           NaN           NaN         NaN         NaN       NaN    NaN  
16717           NaN           NaN         NaN         NaN       NaN    NaN  
16718           NaN           NaN         NaN         NaN       NaN    NaN  

[16719 rows x 16 columns]


(a) Quantos jogos existem em cada genero?


In [237]:
df_games.groupby(['Genre']).size().sort_values(ascending=False)

Genre
Action          3370
Sports          2348
Misc            1750
Role-Playing    1500
Shooter         1323
Adventure       1303
Racing          1249
Platform         888
Simulation       874
Fighting         849
Strategy         683
Puzzle           580
dtype: int64

(b) Temos duplicados nesses dados? E nulos?

In [238]:
df_games.isnull().sum()
#Há valores nulos no df.

Name                  2
Platform              0
Year_of_Release     269
Genre                 2
Publisher            54
NA_Sales              0
EU_Sales              0
JP_Sales              0
Other_Sales           0
Global_Sales          0
Critic_Score       8582
Critic_Count       8582
User_Score         9129
User_Count         9129
Developer          6623
Rating             6769
dtype: int64

In [239]:
#solução professora
df_games.duplicated().sum()

0

In [240]:
df_games_novo = df_games.drop_duplicates()
print(df_games.shape)
print(df_games_novo.shape)
print('Não há duplicados')

(16719, 16)
(16719, 16)
Não há duplicados


(b) Quantos jogos de cada publisher receberam nota acima de 9 na avaliação dos usuarios?

In [241]:
df_games[df_games['User_Score'] > 9.0].groupby('Publisher').agg({'User_Score':np.size}).sort_values(by='User_Score',ascending=False)

User_Score
Publisher                                     
Nintendo                                    20
Electronic Arts                             19
Activision                                  16
Konami Digital Entertainment                10
THQ                                         10
Tecmo Koei                                   9
Capcom                                       9
Vivendi Games                                8
Atari                                        7
Sony Computer Entertainment                  7
Sega                                         7
Namco Bandai Games                           6
Ubisoft                                      5
Midway Games                                 5
Eidos Interactive                            5
Take-Two Interactive                         4
Sony Computer Entertainment Europe           3
PQube                                        2
Acclaim Entertainment                        2
Microsoft Game Studios                       2
Marvelous Interactive                        2
Zoo Digital Publishing                       2
Atlus                                        2
LucasArts                                    1
Sting                                        1
Activision Value                             1
Virgin Interactive                           1
ValuSoft                                     1
Telegames                                    1
Bethesda Softworks                           1
Codemasters                                  1
Destination Software, Inc                    1
Sunflowers                                   1
Square Enix                                  1
Metro 3D                                     1
Square                                       1
Disney Interactive Studios                   1
GT Interactive                               1
Ignition Entertainment                       1
Infogrames                                   1
Interplay                                    1
Jaleco                                       1
Kadokawa Shoten                              1
Kemco                                        1
505 Games                                    1


(c) Faça uma tabela que mostre o total vendido por ano por pais/globalmente de cada publisher? Você consegue observar algum padrão? Com se comportaram as vendas na América do Norte (NA) ao longo do tempo? O mesmo foi visto nos demais lugares? 


In [242]:
df_games.groupby(['Publisher', 'Year_of_Release']).agg({'NA_Sales':np.sum, 'EU_Sales': np.sum, 'JP_Sales': np.sum, 'Other_Sales': np.sum})

NA_Sales  EU_Sales  JP_Sales  \
Publisher                    Year_of_Release                                 
10TACLE Studios              2,006.00             0.01      0.01      0.00   
                             2,007.00             0.06      0.03      0.00   
1C Company                   2,009.00             0.00      0.01      0.00   
                             2,011.00             0.01      0.06      0.00   
20th Century Fox Video Games 1,981.00             1.27      0.07      0.00   
...                                                ...       ...       ...   
imageepoch Inc.              2,014.00             0.00      0.00      0.04   
inXile Entertainment         2,015.00             0.03      0.06      0.00   
mixi, Inc                    2,015.00             0.00      0.00      0.87   
responDESIGN                 2,004.00             0.07      0.02      0.00   
                             2,005.00             0.02      0.02      0.00   

                                              Other_Sales  
Publisher                    Year_of_Release               
10TACLE Studios              2,006.00                0.00  
                             2,007.00                0.00  
1C Company                   2,009.00                0.00  
                             2,011.00                0.01  
20th Century Fox Video Games 1,981.00                0.01  
...                                                   ...  
imageepoch Inc.              2,014.00                0.00  
inXile Entertainment         2,015.00                0.01  
mixi, Inc                    2,015.00                0.00  
responDESIGN                 2,004.00                0.00  
                             2,005.00                0.01  

[2337 rows x 4 columns]


(d) Qual foi jogo mais vendido na união européia? De que ano ele é e qual a editora?


In [243]:
df_games.groupby(['Name','Publisher','Year_of_Release']).agg({'EU_Sales':np.sum}).sort_values(by='EU_Sales', ascending=False).head(1)

EU_Sales
Name       Publisher Year_of_Release          
Wii Sports Nintendo  2,006.00            28.96


(e) Quantos % os generos ['Racing', 'Sports', 'Shooter'] representam na base de dados? 

In [244]:
#Racing
df_games['Global_Sales'][(df_games['Genre'] == 'Racing')].sum() / df_games['Global_Sales'].sum()

0.08171249845857202

In [245]:
#Sports
df_games['Global_Sales'][(df_games['Genre'] == 'Sports')].sum() / df_games['Global_Sales'].sum()

0.14932233220855798

In [246]:
#Shooter
df_games['Global_Sales'][(df_games['Genre'] == 'Shooter')].sum() / df_games['Global_Sales'].sum()

0.11803863098774701

In [247]:
# Total
df_games['Global_Sales'][(df_games['Genre'] == 'Racing') | (df_games['Genre'] == 'Sports') | (df_games['Genre'] == 'Shooter')].sum() / df_games['Global_Sales'].sum()

0.34907346165487707

(f) Qual plataforma vendeu menos globalmente? obs: imprimir somente o nome

In [248]:
print(df_games.groupby(['Platform']).agg({'Global_Sales':np.sum}).sort_values(by='Global_Sales', ascending=True).head(1).index[0])

PCFX


### Problema 5
A pasta 'data/datasus' contém informações sobre casos de dengue e tabelas auxiliares. <br>

| Tabela | Conteúdo |
|--------|----------|
| Dengue | Quantidade de casos por município |
| Agua | Quantidade de residências em cada município por tipo o abastecimento de água |
| InstalacoesSanitarias | Quantidade de residências em cada município por tipo de rede de esgoto |
| Pib | PIB per capita de cada município |
| Municipios | Relaciona o id_municipio com seu nome e estado |
| Populacao | Quantidade de pessoas morando em áreas urbanas, rurais e população total por município |
| Sexo | Quantidade de pessoas por sexo em cada município |

(a) Calcular o número de casos de dengue por cada estado apresentando os dados em ordem decrescente.


(b) Utilizando o dataset InstalacoesSanitarias.csv, determine o número de pessoas que não possuem meio sanitário algum de descarte de dejetos por estado.

(c) Crie uma coluna com a posição de ranking considerando o PIB. Os maiores PIB devem ter os menores valores de ranking.

(d) Qual o PIB dos 5 municípios com mais casos de dengue e sua posição no ranking?